image: chrisb9/php8

before_script:
    - apt update && apt upgrade -y
    - apt install -y zlib1g-dev git libicu-dev zip libzip-dev curl
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - composer install

test:app:
    script:
        - php vendor/bin/phpunit --coverage-text --color tests
