image: docker

variables:
    DOCKER_TLS_CERTDIR: "/certs"
    XDEBUG_MODE: coverage

services:
    - docker:dind

before_script:
    - docker pull registry.agilicode.fr/agilicode/php:8.1-fpm

phpunit:
    script:
        - docker run -v $(pwd):/srv/app --rm registry.agilicode.fr/agilicode/app:8.1-fpm composer install
        - docker run -e XDEBUG_MODE=coverage -v $(pwd):/srv/app --rm registry.agilicode.fr/agilicode/app:8.1-fpm vendor/bin/phpunit -c phpunit.xml --coverage-text --coverage-cobertura=coverage.cobertura.xml --colors=never tests
        - ls -la
    artifacts:
        reports:
            coverage_report:
                coverage_format: cobertura
                path: coverage.cobertura.xml
