image: registry-192-168-1-13.traefik.me/agilicode/php:7.0-fpm

variables:
    XDEBUG_MODE: coverage

phpunit:
    stage: test
    script:
        - php vendor/bin/phpunit -c phpunit.xml --coverage-html coverage --coverage-text --colors=never tests
    artifacts:
        name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
        paths:
            - coverage/
        expire_in: 1 week
