image: php:7.4

variables:
    XDEBUG_MODE: coverage

before_script:
    - apt update && apt upgrade -y
    - apt install -y zlib1g-dev git libicu-dev zip libzip-dev curl
    - pecl install xdebug
    - docker-php-ext-enable xdebug
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - composer install

test:phpunit:
    script:
        - php vendor/bin/phpunit -c phpunit.xml --coverage-text --color tests
