image: registry.agilicode.fr/agilicode/php:8.0-fpm

variables:
    XDEBUG_MODE: coverage

before_script:
    - composer install

phpunit:
    stage: test
    script:
        - php vendor/bin/phpunit -c phpunit.xml --log-junit junit-report.xml --coverage-text --colors=never tests
    artifacts:
        when: always
        reports:
            junit: junit-report.xml
