image: docker

variables:
    DOCKER_TLS_CERTDIR: "/certs"
    XDEBUG_MODE: coverage

services:
    - docker:dind
    - registry.agilicode.fr/agilicode/php:8.0-fpm

before_script:
    - composer install
    - docker login -u $REGISTRY_USR -p $REGISTRY_PWD $REGISTRY_URL

phpunit:
    stage: test
    script:
        - php vendor/bin/phpunit -c phpunit.xml --log-junit junit-report.xml --coverage-text --colors=never tests
    artifacts:
        when: always
        reports:
            junit: junit-report.xml
