image: docker

variables:
    DOCKER_TLS_CERTDIR: "/certs"
    XDEBUG_MODE: coverage

services:
    - docker:dind

before_script:
    - composer install
    - docker login -u $REGISTRY_USR -p $REGISTRY_PWD $REGISTRY_URL
    - docker pull registry.agilicode.fr/agilicode/php:8.0-fpm
    - docker pull registry.agilicode.fr/agilicode/php:8.1-fpm
    - docker pull registry.agilicode.fr/agilicode/php:8.2-fpm
    - docker pull registry.agilicode.fr/agilicode/php:8.3-fpm

phpunit-php8.0:
    stage: test
    script:
        - docker run -v $(pwd):/srv/app --rm registry.agilicode.fr/agilicode/app:8.0-fpm composer install
        - docker run -v $(pwd):/srv/app --rm registry.agilicode.fr/agilicode/app:8.0-fpm vendor/bin/phpunit -c phpunit.xml --log-junit junit-report.xml --coverage-text --colors=never tests
    artifacts:
        when: always
        reports:
            junit: junit-report.xml

phpunit-php8.1:
    stage: test
    script:
        - docker run -v $(pwd):/srv/app --rm registry.agilicode.fr/agilicode/app:8.1-fpm composer install
        - docker run -v $(pwd):/srv/app --rm registry.agilicode.fr/agilicode/app:8.1-fpm vendor/bin/phpunit -c phpunit.xml --log-junit junit-report.xml --coverage-text --colors=never tests
    artifacts:
        when: always
        reports:
            junit: junit-report.xml

phpunit-php8.2:
    stage: test
    script:
        - docker run -v $(pwd):/srv/app --rm registry.agilicode.fr/agilicode/app:8.2-fpm composer install
        - docker run -v $(pwd):/srv/app --rm registry.agilicode.fr/agilicode/app:8.2-fpm vendor/bin/phpunit -c phpunit.xml --log-junit junit-report.xml --coverage-text --colors=never tests
    artifacts:
        when: always
        reports:
            junit: junit-report.xml

phpunit-php8.3:
    stage: test
    script:
        - docker run -v $(pwd):/srv/app --rm registry.agilicode.fr/agilicode/app:8.3-fpm composer install
        - docker run -v $(pwd):/srv/app --rm registry.agilicode.fr/agilicode/app:8.3-fpm vendor/bin/phpunit -c phpunit.xml --log-junit junit-report.xml --coverage-text --colors=never tests
    artifacts:
        when: always
        reports:
            junit: junit-report.xml
