image: docker

variables:
    DOCKER_TLS_CERTDIR: "/certs"

services:
    - docker:dind

before_script:
    - docker pull registry.agilicode.fr/agilicode/php:8.1-fpm

phpunit:
    script:
        - docker run -v $(pwd):/srv/app --rm registry.agilicode.fr/agilicode/app:8.1-fpm composer install
        - docker run -e XDEBUG_MODE=coverage -v $(pwd):/srv/app --rm registry.agilicode.fr/agilicode/app:8.1-fpm vendor/bin/phpunit -c phpunit.xml --coverage-text --coverage-cobertura=coverage.cobertura.xml --log-junit=junit-report.xml tests
        - ls -la
    artifacts:
        when: always
        reports:
            junit: junit-report.xml
            coverage_report:
                coverage_format: cobertura
                path: coverage.cobertura.xml
        expire_in: 1 week
