image: docker

variables:
    DOCKER_TLS_CERTDIR: "/certs"
    XDEBUG_MODE: coverage

services:
    - docker:dind

before_script:
    - docker pull registry.agilicode.fr/agilicode/php:8.0-fpm

phpunit:
    script:
        - docker run -v $(pwd):/srv/app --rm registry.agilicode.fr/agilicode/app:8.0-fpm composer install
        - docker run -v $(pwd):/srv/app --rm registry.agilicode.fr/agilicode/app:8.0-fpm vendor/bin/phpunit -c phpunit.xml --coverage-text --colors=never tests
