image: php:7.4

before_script:
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php');"
    - php composer.phar install

test:app:
    script:
        - php vendor/bin/phpunit tests --color
